name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ffmpeg -version
          ffprobe -version
      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: python3 -B -m unittest discover -s tests -v
